langage: c
sudo: false

env:
  - LUA="lua5.1" LUAC="luac5.1"

addons:
  apt:
    packages:
      - lua5.1

script:
  - cd tests
  - ./lualint.sh
  - ./cs.sh
  - ./globals.sh || true

notifications:
  email:
    on_failure: always
    on_success: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/805c7d220691b76db4ca
    on_success: change
    on_failure: always

cache:
  apt: true
