name: Package and release
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
      - name: Package and release
        uses: BigWigsMods/packager@v2.0.8